Add the ability to customize section and field names on save/load.
burner/inifiled pull request #11
Opened 2018-03-26 20:48 UTC by Hackerpilot

Fixes #1. Also fixes some spelling mistakes.

2018-03-26 21:51 UTC, BBasile commented
@burner, if you take this PR please also push a new git tag for DUB. We actually require it for D-Scanner.

2018-03-28 06:46 UTC, burner commented
apart of the nitpicks it looks good. thank you.
As soon as these are fixed I'm gone merge and push a new tag.

2018-03-28 06:46 UTC, burner requested changes

2018-03-28 06:46 UTC, burner commented on source/inifiled.d
> +		if (hasUDA!(T, INI))
could you move the { to the end of the line

2018-03-28 06:46 UTC, burner commented on source/inifiled.d
> +			else
could you please add curly braces for the two else statements

2018-03-29 07:33 UTC, burner approved these changes

2018-03-29 07:33 UTC, merged

2018-03-29 07:33 UTC, burner commented
@Hackerpilot thank you

2018-03-29 07:45 UTC, burner commented
new tag is pushed